---
# This is the checkov workflow with actions
on: [push]  # yamllint disable-line rule:truthy
jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: yamllint
        uses: docker://ghcr.io/ffurrer2/yamllint:latest
        with:
          args: '--format standard .'
  checkov-job:
    needs: yamllint
    runs-on: ubuntu-latest
    name: checkov-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      - name: wget the config file
        # yamllint disable
        run: mkdir config && wget -O config/checkov_config.yaml https://raw.githubusercontent.com/sun1l-aries/iac_checkov/master/config_output.yaml
        # yamllint enable
      - name: pull the docker
        run: docker pull bridgecrew/checkov
      - name: mount the 2 volumes and run checkov
        # yamllint disable
        run: docker run --tty --volume $(pwd):/tf --workdir /tf bridgecrew/checkov --config-file /tf/config/checkov_config.yaml
        # yamllint enable
